### ISSUE TITLE
No option to "explode" an array into individual elements

### ISSUE THREAD

**Issue by didiergm** [APEbbers/BillOfMaterials-WB#49]
When, in A2Plus, importing an array of objects, the BOM list the array as one single element, which makes the BOM feel wrong, especially when the width, length and pad will be evaluated the calculation one could derive from these values will be off by possibly a long way

Not knowing the internals of Freecad I don't know if it would be feasible or not to explode an array into it's component elements or if there would be a work around

Edit: I was thinking may be just extracting the length of the array could go a long way into mitigating what I see as an issue (does not mean everybody would), mays be as an extra column, defaulting to 1; if it is not an array

**Comment by APEbbers** [comment]
I believe you talking about "etageres_basse_Array_001"?  Here you have create a part with two separate bodies. This not the same as an assembly. In this case it is better to create one part with just one body and add it twice in the assembly or create a subassembly with these parts. This is because your part with two bodies is a "MultiBody" part.

At the moment this is a different type of Bom. When you create a BoM in t"etageres_basse_Array_001", you will see that MultiBody is selected instead of the A2plus. Then you will get a BoM of different bodies.

I have planned to write a function to combine all different assembly types into one function. But first I want to have all the necessary functions implemented as well do some more bug checking. It quite a difficult function to write. So I want to be sure that the WB works for the all the assemblies separately.
