### ISSUE TITLE
Question regarding sub assemblies

### ISSUE THREAD

**Issue by didiergm** [APEbbers/BillOfMaterials-WB#60]
In a2Plus, the subassembly **content** is listed fine, identified by a number with a dot in it, that works really well, but the subassembly itself is also listed, which confuses the reader, and makes it a bit difficult to read / understand, may be an option to list or not the subassembly. what do you think ?

This is in the full BOM list

**Comment by APEbbers** [comment]
It is common practices to include the subassembly. This is because when you don't include the subassemblies them self, you will see their content, but you cannot see to which subassembly they belong to.

This is not desired because in companies, the full BOM is ment to show the complete structure of your assembly including it's subassemblies. Often a full bom is used as a drawing list or a list from which parts and subassemblies are ordered by a supplier.
The drawing of subassembly is then used for assembling instructions.

For now, I pause this option. However, if you enable the "Enable extra columns for debug".  The item type will be shown. (Part, body or assembly). 
![image](https://github.com/APEbbers/BillOfMaterials-WB/assets/10145631/7a46de52-3d69-4e3b-8327-66cddd733611)

When you copy the bill of materials to Excel or equivalent, you can filter with the item types.
I have an export function planned. Also I will add "item type" as standard to the dialog for setting the columns.

**Comment by didiergm** [comment]
Sounds good enough, I did not know including subassembly was an industry-standard

**Comment by didiergm** [comment]
When trying - the extra column which does not have any heading, btw) is always empty (
